PSPSDK = ${shell psp-config --pspsdk-path}

BUILD_PRX = 1

PSP_FW_VERSION = 371
PSP_LARGE_MEMORY = 1

PSP_EBOOT_TITLE = TempGBA-mod Single-Game Launcher

EXTRA_TARGETS = EBOOT.PBP

OBJS = main.o

TARGET = TempGBA-mod_Single-Game_Launcher

LIBS = -lpspsystemctrl_user

include ${PSPSDK}/lib/build.mak
